# Generated by Django 5.1.1 on 2024-12-12 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="branch",
            new_name="brand",
        ),
    ]
